name: panda-gadget-thymythos
version: 2017.01
summary: Pandaboard support package
description: |
 Support files for booting Pandaboard
type: gadget
architectures: [armhf]
confinement: strict
grade: stable
parts:
  uboot:
    plugin: kbuild
    source: git://git.denx.de/u-boot.git
    source-tag: v2017.01
    source-depth: 1
    kdefconfig: [omap4_panda_defconfig]
    build-attributes:
      - no-install
    prepare: |
      sed '44 a #define CONFIG_SYS_REDUNDAND_ENVIRONMENT' -i include/configs/omap4_panda.h
    install: |
      cp MLO u-boot.img $SNAPCRAFT_PART_INSTALL/
      tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/uboot.env ../../../uboot.env.in
      ln -s uboot.env $SNAPCRAFT_PART_INSTALL/uboot.conf
    build-packages:
      - bc
      - build-essential
      - libpython2.7-dev

slots:
  gpio-20:
    interface: gpio
    number: 20
  i2c-3:
    interface: i2c
    path: /dev/i2c-3
  bt-serial:
    interface: serial-port
    path: /dev/ttyO1
  ext-serial:
    interface: serial-port
    path: /dev/ttyO3
  spidev0.0:
     interface: spi
     path: /dev/spidev0.0
  spidev0.1:
     interface: spi
     path: /dev/spidev0.1
